apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-go
  labels:
    app: cloud-go
spec: 
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-go 
        tier: service
    spec: 
      containers: 
      - name: cloud-go
        image: "johnantonusmaximus/cloud-go:1.0.1"
        ports:
        - containerPort: 9090
        env:
        - name: PORT 
          value: "9090"

        # define resource requests and limits 
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"

        # define readiness and liveness probes
        readinessProbe:
          httpGet:
            path: /ping 
            port: 9090
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /ping 
            port: 9090
          initialDelaySeconds: 5
          timeoutSeconds: 5